### ISSUE TITLE
Auto completion issue during typing

### ISSUE THREAD

**Issue by tempelmann** [tempelmann/custom-editfield#10]
Reported by rogermeier:

v1.7.8 still appears to have this issue. I attached a screenshot.
![screen shot 2015-03-23 at 11 14 17 pm](https://cloud.githubusercontent.com/assets/194280/6796558/60019bc0-d1b2-11e4-84ab-2846667694db.png)

----
Reply by tempelmann:

the bug report suggests that this only happens with indented code, while your screenshot shows a line without indentation, so it might even have a different cause. For instance, do you build for Carbon or Cocoa? I can imagine that Cocoa has other font metrics and that the way CEF measures them is incompatible. I remember having had troubles with font width measurement in Cocoa before.

----
Reply by rogermeier:

I think you're right in this may be another issue altogether. This issue is not platform dependent as I'm also seeing this on Win7:
![clipboard_2015-03-24_09-32-51](https://cloud.githubusercontent.com/assets/194280/6806917/d1439c92-d208-11e4-8940-e0873f027222.png)
What's interesting is that it only occurs when typing keys. For example, the above image shows the screen after typing "someoth". However, when using the backspace key, the autocomplete text is properly aligned. The image below shows the same screen after deleting the "h" with backspace:
![clipboard_2015-03-24_09-35-56](https://cloud.githubusercontent.com/assets/194280/6807023/38d6f494-d209-11e4-9154-a58d622da01e.png)
It behaves identically on Mac and Windows.
I'll dig through the code to see if I can find anything.

----
Reply by rogermeier:

I think I'm stuck. Here is what I was able to find:
- drawContents uses the AutocompleteSuggestionInsertionX property to determine where do draw the autocomple suggestion. When a key is typed, this property is seemingly not updated to reflect the just added character.
- AutocompleteSuggestionInsertionX is updated in the AutoCompleteEOL method, which executes as a result of the keydown event, prior to drawContents.
- AutoCompleteEOL calls XYAtCharPos to update AutocompleteSuggestionInsertionX.
- XYAtCharPos calls XposForOffset for the current line to calculate the x position.
- XposForOffset the calls TextLine.TextWidth, which is where the issue appears to happen. If I inspect the text variable in TextLine.TextWidth it does not contain the typed character yet.

It appears that, at the time AutoCompleteEOL is executed after a new character is typed, the TextLine that is used to calculate where the autocomplete suggestion needs to go doesn't contain the new character yet. However, I have not been able to figure why that is exactly. 

The call stack is as follows when a new character is pressed:
CustomEditField.AutoCompleteEOL
CustomEditField.changeSelection
CustomEditField.private_replace
CustomEditField.Insert
CustomEditField.HandleKeyDown
CustomEditField.Event.KeyDown

And here is the call stack when backspace is pressed (and autocomplete works):
CustomEditField.AutoCompleteEOL
CustomEditField.changeSelection
CustomEditField.private_remove
CustomEditField.DeleteChars
CustomEditField.HandleKeyDown
CustomEditField.Event.KeyDown

If I had to guess, I would say the difference is somewhere in either .private_replace or .insert, but I can't figure out where.

**Comment by tempelmann** [comment]
Fixed along with Issue #9 by today's commit.

**Comment by rogermeier** [comment]
I can confirm that the latest commit resolves the issue I was seeing. Nicely done! Thank you very much!

Roger
