### ISSUE TITLE
Canvas only refreshing on resize

### ISSUE THREAD

**Issue by gkjpettet** [tempelmann/custom-editfield#23]
I can't seem to get the CEF to display anything I type (even when the CEF has the focus). As soon as I resize the window that the CEF is within, the text I typed shows up as expected.

This is using 2015 R2.2 on Mac 10.10.4 with an empty Xojo project. I simply dragged the CustomEditField folder from the demo app to a new project and then dragged an instance of the CEF to a new window. The CEF demo app works as expected.

What am I doing wrong?

**Comment by tempelmann** [comment]
Odd. I see the same problem. No idea. Maybe some property you need to set as well. Compare the properties of the control in your new window with those of the demo project. Let me know what you find. Sorry, I don't have time to look myself but if you find the solution, I will make a note to fix this soon. Best if you open a ticket where you explain what needs fixing.

**Comment by gkjpettet** [comment]
I have mimicked every option with the demo project and have systematically commented out the implemented CEF event handlers in the demo project but I still can't get it to work. This is essentially unusable in it's current state. Bummer.

**Comment by tempelmann** [comment]
I wonder if it has to do with some double buffering mode.

**Comment by gkjpettet** [comment]
Just tried every permutation of me.DoubleBuffer and me.EraseBackground in the CEF subclass Open event to no avail. This is so bizarre

**Comment by gkjpettet** [comment]
I think I've found the issue but not sure of the safest way to fix it. If you comment out the first line in CustomEditField.Redraw():

`if ignoreRepaint and not forced then Return

Then it works. Thoughts

**Comment by tempelmann** [comment]
I don't think that's it. Here's some more testing I did:

Using REAL Studio 2012r2.1, I open the CEF project, select the "CustomEditField" folder, copiy it to the clipboard. Create new desktop project, paste the folder into it. Open Window1 layout editor, add the CustomEditField control, run the project. Typing is visible.

Doing the very step steps in Xojo 2015r2.2 leads to invisible typing.

But when I save the project and re-open it, the typing becomes visible.

I'd blame it on Xojo.

Can you reproduce this?

**Comment by gkjpettet** [comment]
Yep. Confirmed. Saving the project then quitting and relaunching Xojo solves the problem.

**Comment by tempelmann** [comment]
Great. So, let's assume that this is not a CEF issue but a bug in Xojo. I'll update the Instructions.
