### ISSUE TITLE
64 Bit on OS X

### ISSUE THREAD

**Issue by cmwade77** [tempelmann/custom-editfield#25]
Overall, I think that this would wok, there are just a few error messages when compiling for 64 Bit on OS X:

`Undefined symbols for architecture x86_64:  "_SetDragImageWithCGImage", referenced from:_DragImage.$SetImage%%o<DragItem>o<Picture> in DragImage.o
ld: symbol(s) not found for architecture x86_64`

`Undefined symbols for architecture x86_64:  "_SetDragImageWithCGImage", referenced from:"_QDBeginCGContext", referenced from:
ld: symbol(s) not found for architecture `x86_64`

`Undefined symbols for architecture x86_64:  "_SetDragImageWithCGImage", referenced from:_DragImage.NewCGImage%p%o<Picture> in DragImage.o
ld: symbol(s) not found for architecture x86_64`

`Undefined symbols for architecture x86_64:  "_SetDragImageWithCGImage", referenced from:"_QDEndCGContext", referenced from:
ld: symbol(s) not found for architecture x86_64`

`Undefined symbols for architecture x86_64:  "_SetDragImageWithCGImage", referenced from:_DragImage.NewCGImage%p%o<Picture> in DragImage.o
ld: symbol(s) not found for architecture x86_64`

**Comment by tempelmann** [comment]
And I guess that Xojo still has not added a way to set the dragged image on a DragItem object? We might just remove that SetImage call for now - it doesn't seem to make a difference anyway.
